/*
SQL Exploratory Data Analysis (EDA) Project

Skills used: Basic Queries, Data Profiling, Simple Aggregations, Suqueries

*/

--
-- 1.Database Exploration
--

-- Explore All objects in the database

SELECT * FROM INFORMATION_SCHEMA.TABLES;

SHOW TABLES FROM eda_portfolioproject;

-- Explore All columns in the database

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';

--
-- 2. Dimension Exploration
--

-- Explore All countries our customer come from.
 SELECT DISTINCT country
FROM dim_customers;

-- Explore All Categories “The major Divisions”
SELECT DISTINCT category
FROM dim_products;

SELECT DISTINCT category, subcategory, product_name
FROM dim_products;

SELECT COUNT(DISTINCT category) AS num_category, 
	COUNT(DISTINCT subcategory) AS num_subcategory, 
    COUNT(DISTINCT product_name) AS num_product
FROM dim_products
ORDER BY 1;

SELECT category, 
	COUNT(DISTINCT subcategory) AS num_subcategory, 
    COUNT(DISTINCT product_name) AS num_product
FROM dim_products
WHERE category <> ''
GROUP BY category
ORDER BY 1;

--
-- 3. Date Exploration: Understand the scope of data and the timespan.
--

-- Idntify the earliest and latest dates (boundaries)
SELECT 
	MIN(order_date) AS first_order_date,
    MAX(order_date) AS last_order_date
FROM fact_sales;

-- How many years of sales are available
SELECT 
	MIN(order_date) AS first_order_date,
    MAX(order_date) AS last_order_date,
    TIMESTAMPDIFF(YEAR,MIN(order_date),MAX(order_date)) AS order_range_years,
    TIMESTAMPDIFF(Month,MIN(order_date),MAX(order_date)) AS order_range_months
FROM fact_sales
WHERE order_date <> '';

-- Find the youngest and oldest customers
SELECT 
	MIN(birthdate) AS oldest_birthdate,
    TIMESTAMPDIFF(YEAR,MIN(birthdate), CURDATE()) AS oldest_age,
    MAX(birthdate) AS young_birthdate,
	TIMESTAMPDIFF(YEAR,MAX(birthdate), CURDATE()) AS youngest_age
FROM dim_customers
WHERE birthdate <> '';



--
-- 4. Measure Exploration: Calculate the key metric of the business (big numbers)
-- 
SELECT * FROM fact_sales;

-- Find the Total Sales
SELECT SUM(sales_amount) AS total_sales
FROM fact_sales;

-- Find how many items are sold
SELECT SUM(quantity) AS total_quanatity
FROM fact_sales;

-- Find the average selling price
SELECT AVG(price) AS avg_price
FROM fact_sales;

-- Find the Total numbers of orders
SELECT COUNT(DISTINCT order_number) AS total_orders
FROM fact_sales;

-- Find the Total numbers of products
SELECT COUNT(DISTINCT product_key ) AS total_products
FROM dim_products;

-- Find the Total numbers of customers
SELECT COUNT(DISTINCT customer_key ) AS total_customers
FROM dim_customers;

-- Find the Total numbers of customers that has placed an order
SELECT COUNT(DISTINCT customer_key ) AS total_customers
FROM fact_sales;

-- Generate a Report that shows all key metric of the business
SELECT 'Total Sales' AS KPI_Name, FORMAT(SUM(sales_amount), 0) AS KPI_values FROM fact_sales
UNION ALL 
SELECT 'Total Quantity' AS KPI_Name, FORMAT(SUM(quantity), 0) AS KPI_values FROM fact_sales
UNION ALL 
SELECT 'Average Price' AS KPI_Name, FORMAT(AVG(price), 2) AS KPI_values FROM fact_sales
UNION ALL 
SELECT 'Total Orders' AS KPI_Name, FORMAT(COUNT(DISTINCT order_number), 0) AS KPI_values FROM fact_sales
UNION ALL 
SELECT 'Total Products' AS KPI_Name, FORMAT(COUNT(DISTINCT product_key), 0) AS KPI_values FROM dim_products
UNION ALL 
SELECT 'Total Customers' AS KPI_Name, FORMAT(COUNT(DISTINCT customer_key), 0) AS KPI_values FROM dim_customers;

--
-- 5. Magnitude: Compare the measure values by categories
-- To understand the importance of different categories 

SELECT * FROM dim_customers;

-- Find total customers by country
SELECT
	country,
    COUNT(customer_key) AS total_customers
FROM dim_customers
GROUP BY 1
ORDER BY 2 DESC;

-- Find total customers by gender
SELECT
	gender,
    COUNT(customer_key) AS total_customers
FROM dim_customers
GROUP BY 1
ORDER BY 2 DESC;

-- Find total products by category
SELECT * FROM dim_products;

SELECT
	category,
    COUNT(product_key) AS total_products
FROM dim_products
GROUP BY 1
ORDER BY 2 DESC;

-- What is the average cost in each category?
SELECT
	category,
    AVG(cost) AS avg_cost
FROM dim_products
GROUP BY 1
ORDER BY 2 DESC;

-- What is the total revenue generated for each category?
SELECT 
	p.category,
    SUM(f.sales_amount) AS total_revenue
FROM fact_sales f
LEFT JOIN dim_products p
	ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Find total revenue is generated by each customer
SELECT 
	c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM fact_sales f
LEFT JOIN dim_customers c
	ON f.customer_key = c.customer_key
GROUP BY 1,2,3 
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT * FROM fact_sales;
SELECT * FROM dim_customers;
SELECT * FROM dim_products;

SELECT 
	c.country,
    SUM(f.quantity) AS total_items_sold
FROM fact_sales f
LEFT JOIN dim_customers c
	ON f.customer_key = c.customer_key
GROUP BY 1
ORDER BY 2 DESC;

--
-- 6. Ranking Analysis: 
--

-- Which 5 products [Dimension] generate the highest revenue [Measure]? >> LIMIT

SELECT
p.product_name,
SUM(f.sales_amount) AS total_revenue  
FROM fact_sales f
LEFT JOIN dim_products p
	ON f.product_key = p.product_key
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;


-- Which 5 subcategory generate the highest revenue?
SELECT
p.subcategory,
SUM(f.sales_amount) AS total_revenue  
FROM fact_sales f
LEFT JOIN dim_products p
	ON f.product_key = p.product_key
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;

-- What are the 5 worst-performing products in terms of sales?
SELECT
p.product_name,
SUM(f.sales_amount) AS total_revenue  
FROM fact_sales f
LEFT JOIN dim_products p
	ON f.product_key = p.product_key
GROUP BY 1
ORDER BY 2
LIMIT 5;


-- Ranking Products by the highest revenue? >> Window Function: ROW_NUMBER () | RANK()
SELECT
p.product_name,
SUM(f.sales_amount) AS total_revenue,
ROW_NUMBER() OVER (ORDER BY sum(f.sales_amount) DESC) AS rank_products 
FROM fact_sales f
LEFT JOIN dim_products p
	ON f.product_key = p.product_key
GROUP BY 1;

SELECT
p.product_name,
SUM(f.sales_amount) AS total_revenue,
RANK() OVER (ORDER BY sum(f.sales_amount) DESC) AS rank_products 
FROM fact_sales f
LEFT JOIN dim_products p
	ON f.product_key = p.product_key
GROUP BY 1;


-- Top 5 Products by highest revenue >> Subqueries
SELECT * 
FROM (
SELECT
p.product_name,
SUM(f.sales_amount) AS total_revenue,
ROW_NUMBER() OVER (ORDER BY sum(f.sales_amount) DESC) AS rank_products 
FROM fact_sales f
LEFT JOIN dim_products p
	ON f.product_key = p.product_key
GROUP BY 1) t
WHERE rank_products <= 5;



-- Find the top 10 customers who have generated the highest revenue
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue  
FROM fact_sales f
LEFT JOIN dim_customers c
	ON f.customer_key = c.customer_key
GROUP BY 1,2,3
ORDER BY 4 DESC
LIMIT 10;

-- The 3 customers with the fewest orders placed
SELECT
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) AS total_orders  
FROM fact_sales f
LEFT JOIN dim_customers c
	ON f.customer_key = c.customer_key
GROUP BY 1,2,3
ORDER BY 4
LIMIT 3;